# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tweet-button"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy McAnally"]
  s.date = "2012-05-03"
  s.description = "Generate Tweet buttons for your Rails apps"
  s.email = "jeremymcanally@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/tweet-button.rb",
    "lib/tweet-button/railitie.rb",
    "test/helper.rb",
    "test/test_tweet-button.rb",
    "tweet-button.gemspec"
  ]
  s.homepage = "http://github.com/jm/tweet-button"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Generate new Twitter 'Tweet buttons'"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

